all:
#	pandoc -t slidy -s slides.md --self-contained -o slidy.html
#	pandoc -t s5 -s slides.md --self-contained -o s5.html
#	pandoc -t dzslides -s slides.md --self-contained -o dzslides.html
	pandoc -t beamer Slides.md --pdf-engine=xelatex -V aspectratio=169 -V mainfont="Liberation Sans" -V theme:Warsaw -o kicad-workshop.pdf
